export const PROJECT_CURRENT_USER_PROJECTS_REQUEST =
  "PROJECT_CURRENT_USER_PROJECTS_REQUEST";
export const PROJECT_CURRENT_USER_PROJECTS_SUCCESS =
  "PROJECT_CURRENT_USER_PROJECTS_SUCCESS";
export const PROJECT_CURRENT_USER_PROJECTS_FAIL =
  "PROJECT_CURRENT_USER_PROJECTS_FAIL";
export const PROJECT_CLEAR_CURRENT_USER_PROJECTS =
  "PROJECT_CLEAR_CURRENT_USER_PROJECTS";
