export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_AUTHENTICATION_REQUEST = "USER_AUTHENTICATION_REQUEST";
export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_FAIL = "USER_AUTHENTICATION_FAIL";

export const USER_CURRENT_INFORMATION_REQUEST =
  "USER_CURRENT_INFORMATION_REQUEST";
export const USER_CURRENT_INFORMATION_SUCCESS =
  "USER_CURRENT_INFORMATION_SUCCESS";
export const USER_CURRENT_INFORMATION_FAIL = "USER_CURRENT_INFORMATION_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
