export const USER_REGISTRATION_REQUEST = "USER_REGISTRATION_REQUEST";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_AUTHENTICATION_REQUEST = "USER_AUTHENTICATION_REQUEST";
export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_FAIL = "USER_AUTHENTICATION_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_CLEAR_CURRENT = "USER_CLEAR_CURRENT";
